module LeadersHelper
  def eventtypes
    [
      'CommitCommentEvent',
      'CreateEvent',
      'DeleteEvent',
      'DeploymentEvent',
      'DeploymentStatusEvent',
      'DownloadEvent',
      'FollowEvent',
      'ForkEvent',
      'ForkApplyEvent',
      'GistEvent',
      'GollumEvent',
      'IssueCommentEvent',
      'IssuesEvent',
      'LabelEvent',
      'MemberEvent',
      'MembershipEvent',
      'MilestoneEvent',
      'OrganizationEvent',
      'OrgBlockEvent',
      'PageBuildEvent',
      'ProjectCardEvent',
      'ProjectColumnEvent',
      'ProjectEvent',
      'PublicEvent',
      'PullRequestEvent',
      'PullRequestReviewCommentEvent',
      'PushEvent',
      'ReleaseEvent',
      'RepositoryEvent',
      'StatusEvent',
      'TeamEvent',
      'TeamAddEvent',
      'WatchEvent'
    ]
  end
end
